set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

if(NOT DEFINED SPACEMIT_TOOLCHAIN_ROOT)
  if(DEFINED ENV{SPACEMIT_TOOLCHAIN_ROOT})
    set(SPACEMIT_TOOLCHAIN_ROOT "$ENV{SPACEMIT_TOOLCHAIN_ROOT}")
  else()
    message(FATAL_ERROR "Set SPACEMIT_TOOLCHAIN_ROOT to the unpacked SpacemiT Linux/glibc toolchain")
  endif()
endif()
get_filename_component(SPACEMIT_TOOLCHAIN_ROOT "${SPACEMIT_TOOLCHAIN_ROOT}" ABSOLUTE)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES SPACEMIT_TOOLCHAIN_ROOT SPACEMIT_SYSROOT)

set(_bin "${SPACEMIT_TOOLCHAIN_ROOT}/bin")
if(EXISTS "${_bin}/riscv64-unknown-linux-gnu-clang")
  set(CMAKE_C_COMPILER "${_bin}/riscv64-unknown-linux-gnu-clang")
  set(CMAKE_CXX_COMPILER "${_bin}/riscv64-unknown-linux-gnu-clang++")
else()
  set(CMAKE_C_COMPILER "${_bin}/clang")
  set(CMAKE_CXX_COMPILER "${_bin}/clang++")
endif()
if(NOT EXISTS "${CMAKE_C_COMPILER}" OR NOT EXISTS "${CMAKE_CXX_COMPILER}")
  message(FATAL_ERROR "SpacemiT Clang/Clang++ not found under ${_bin}")
endif()

set(CMAKE_C_COMPILER_TARGET riscv64-unknown-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET riscv64-unknown-linux-gnu)
if(NOT DEFINED SPACEMIT_SYSROOT)
  set(SPACEMIT_SYSROOT "${SPACEMIT_TOOLCHAIN_ROOT}/sysroot")
endif()
if(NOT IS_DIRECTORY "${SPACEMIT_SYSROOT}")
  message(FATAL_ERROR "RISC-V Linux sysroot not found: ${SPACEMIT_SYSROOT}")
endif()
set(CMAKE_SYSROOT "${SPACEMIT_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${SPACEMIT_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(_k1_flags "-mcpu=spacemit-x60 -march=rv64gcv_zba_zbb_zbc_zbs_zicbop -mabi=lp64d -mllvm -cache-line-size=64 -mllvm -prefetch-distance=128")
set(CMAKE_C_FLAGS_INIT "${_k1_flags}")
set(CMAKE_CXX_FLAGS_INIT "${_k1_flags}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
